### ISSUE TITLE
€ symbol in a line over 120 characters induce `Error: Invalid point encountered!`

### ISSUE THREAD

**Issue by miniwark** [AtomLinter/linter-phpcs#211]
The following PHP code in a file brake linter-phpcs v1.5.2

```
<?php

if (true) {
    $var1 = 500;
    if ($var1 >= 0) {
        $var2 = 'A short string with the € symbol';
    } elseif ($var1 < 0) {
        $var2 = 'A long string with the € symbol inside. This too long string also make the line exceeds 120 characters.';
    }
}

```

The line 8 have a string with the € symbol inside and the line exceed 120 characters.

When editing or saving the file, this induce the following error message:

```
Error: Invalid point encountered! See console for details.
    at Error (native)
    at /home/username/.atom/packages/linter-phpcs/lib/main.js:338:19
    at Array.map (native)
    at Object.<anonymous> (/home/username/.atom/packages/linter-phpcs/lib/main.js:312:25)
    at undefined.next (native)
    at step (/home/username/.atom/packages/linter-phpcs/lib/main.js:9:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

cf . issue #204 for reference.

**Comment by Arcanemagus** [comment]
What does it show in the console?

**Comment by bntmchr** [comment]
I have a similar problem on saving my script.
Atom gives me the following Error:

```
Error: Invalid point encountered! See console for details.
    at Error (native)
    at /Users/USERNAME/.atom/packages/linter-phpcs/lib/main.js:335:19
    at Array.map (native)
    at Object.<anonymous> (/Users/USERNAME/.atom/packages/linter-phpcs/lib/main.js:309:25)
    at undefined.next (native)
    at step (/Users/USERNAME/.atom/packages/linter-phpcs/lib/main.js:9:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

And the console says the following:

```
main.js [sm]:325 
linter-phpcs:: Invalid point encountered in the attached message 
Object {message: Object, source: Object}
(anonymous function)	@	main.js [sm]:325
(anonymous function)	@	main.js [sm]:309
step	@	/Users/USERNAME/.atom/packages/linter-phpcs/lib/main.js:9
_tickCallback	@	internal/process/next_tick.js:103
```

The Error is shown since updating to version 1.5. I am currently using linter-phpcs version 1.5.3 on Atom 1.11.1.

**Comment by miniwark** [comment]
@Arcanemagus here is the console message ( `__proto__: Object` not expanded):

```
linter-phpcs::  /home/username/.atom/packages/linter-phpcs/lib/main.js:323
Invalid point encountered in the attached message
Object
    message: Object
        column: 124
        fixable: false
        line: 8
        message: "Line exceeds 120 characters; contains 124 characters"
        severity: 5
        source: "Generic.Files.LineLength.TooLong"
        type: "WARNING"
        __proto__: Object
    source: Objectline
        Length: 122
        lineText: "        $var2 = 'A long string with the € symbol inside. This too long string also make the line exceeds 120 characters.';"
        __proto__: Object
    __proto__: Object
    (anonymous function) @ /home/username/.atom/packages/linter-phpcs/lib/main.js:323
```

**Comment by miniwark** [comment]
@Arcanemagus and now the message for v1.5.3  ( `__proto__: Object` not expanded):

```
linter-phpcs:: Invalid point encountered in the attached message main.js [sm]:328 
Object {message: Object, source: Object}
    message: Object
        column: 124
        fixable: false
        line: 8
        message: "Line exceeds 120 characters; contains 124 characters"
        severity: 5
        source: "Generic.Files.LineLength.TooLong"
        type: "WARNING"
        __proto__: Object
    source: Object
        lineLength: 122
        lineText: "        $var2 = 'A long string with the € symbol inside. This too long string also make the line exceeds 120 characters.';"
        __proto__: Object
    __proto__: Object
(anonymous function) @ main.js [sm]:328
(anonymous function) @ main.js [sm]:312
step                 @ /home/username/.atom/packages/linter-phpcs/lib/main.js:9
_tickCallback        @ internal/process/next_tick.js:103
```

**Comment by rayward** [comment]
I've encountered this error also, it looks like its just not handling multibyte characters properly.

Not a JS expert, but I think its naively using `string.length` which may not account for multibyte characters which may be more than 8 bytes.

**Comment by Arcanemagus** [comment]
@rayward I'd be rather shocked if the bug was in Atom as I know it handles those characters perfectly fine. PHPCS on the other hand is pretty bad about handling characters, so I'm almost certain this is a bug in that, I just haven't had time to verify that yet.

**Comment by goodpic** [comment]
Same here with linter-phpcs v1.5.3 & Atom 1.11.2.
It shows the "Error: Invalid point encountered!" when I save a php file which has multi byte chars ( Japanese characters ) AND several phpcs warnings. If I remove either of the multi byte chars, or the warnings, it does save without any error.

```php
} else if (strpos($body, '<th>在庫:</th>', 40000)) {
      $result = 'Available';
} else {
      $result = 'Unavaible';
}
```
So my workaround at this moment is not make the php file pass the lint 100%..

**Comment by jyggen** [comment]
What versions of PHP and PHP_CodeSniffer are you running? I'm running linter-phpcs 1.5.3 on Atom 1.12.0-beta4 locally with PHP 7.0.12 and PHP_CodeSniffer 2.7.0 and can not reproduce it with the code in the issue's description.

**Comment by goodpic** [comment]
Here are mine ( linter-phpcs v1.5.3 & Atom 1.11.2. ).
```zsh
% brew info php-code-sniffer
homebrew/php/php-code-sniffer: stable 2.6.0 (bottled)

% php -v
PHP 5.6.21 (cli) (built: May 17 2016 19:25:12) 
```

**Comment by miniwark** [comment]
```php -v ```
> PHP 7.0.12-1+deb.sury.org~xenial+1 (cli) ( NTS )
(install via `apt`)

```phpcs --version```
> PHP_CodeSniffer version 2.6.2 (stable) by Squiz (http://www.squiz.net)
(install via `composer`)

Do you want me to test the upgrade to PHP_CodeSniffer 2.7 ?

**Comment by pixolin** [comment]
I have the same issue here, using 
PHP_CodeSniffer version 2.7.0 (stable) and 
PHP 5.6.25 (cli) (built: Sep  6 2016 16:37:16)
on my Mac.
Error message shows
```
Error: Invalid point encountered! See console for details.
    at Error (native)
    at /Users/bego/Dropbox/Apps/Atom/packages/linter-phpcs/lib/main.js:335:19
    at Array.map (native)
    at Object.<anonymous> (/Users/bego/Dropbox/Apps/Atom/packages/linter-phpcs/lib/main.js:309:25)
    at undefined.next (native)
    at step (/Users/bego/Dropbox/Apps/Atom/packages/linter-phpcs/lib/main.js:9:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
just like already reported by @bntmchr.

**Comment by nelson6e65** [comment]
I'm getting this error too. In console:

![pantallazo-2016-11-08 01-49-55](https://cloud.githubusercontent.com/assets/9272498/20088515/d994f9e0-a556-11e6-81a0-371df799d37a.png)

`inter-phpcs:: Invalid point encountered in the attached message`

```json
"message": {
  "message": "Line exceeds 120 characters; contains 150 characters"
},
"source": {
  "lineLength": 148
  "lineText": "    app_exit(404, null, "El controlador <strong><code>$Controller</code></strong> no tiene ningún método '<strong><code>$action</code></strong>'.");"
}
```

Notice that `lineText` do not scapes quotes.


Referenced line in PHP:
```php
<?php
// . . .
    app_exit(404, null, "El controlador <strong><code>$Controller</code></strong> no tiene ningún método '<strong><code>$action</code></strong>'.");
```

**Comment by irudoy** [comment]
Same issue, same error message.

macOS 10.12.1
Atom 1.12.0
PHP_CodeSniffer version 2.7.0 (stable)
PHP 7.0.12

**Comment by nonDeath** [comment]
The same issue when i put the next regexp in the file

```PHP
$regex = "/^[0-9a-zA-ZáéíóúüñÁÉÍÓÚÜÑ]+[0-9a-zA-ZáéíóúüñÁÉÍÓÚÜÑ\ \-\_\.\@\']*[0-9a-zA-ZáéíóúüñÁÉÍÓÚÜÑ]+$/";

```
But when i split these into two lines the error disapear.

**Comment by AivahThemes** [comment]
Same here with the following error

`Error: Invalid point encountered! See console for details.
Error: Invalid point encountered! See console for details.
    at Error (native)
    at C:/Users/fem/.atom/packages/linter-phpcs/lib/main.js:335:19
    at Array.map (native)
    at Object.<anonymous> (C:/Users/fem/.atom/packages/linter-phpcs/lib/main.js:309:25)
    at next (<anonymous>)
    at step (C:\Users\fem\.atom\packages\linter-phpcs\lib\main.js:9:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)`

### Below are the Info on the Application Versions

Atom 1.12.2
linter-phpcs 1.5.3
Wampserver 2.5
PHP 5.5.12
_Coding Standard or Config file **WordPress-Core**_ from https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards

**Comment by mainos1** [comment]
I experienced similar problems. The solution for me was to set the default encoding for PHP_CodeSniffer:
`$ phpcs --config-set encoding utf-8`

check [https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-default-encoding](url)

**Comment by nelson6e65** [comment]
Thanks, @mainos1 I'll try.

**Comment by Tokimon** [comment]
couldn't the `--encoding utf8` parameter be added?
(as mentioned in #227)

**Comment by weirdan** [comment]
> couldn't the --encoding utf8 parameter be added?

Or, better yet, pass `textEditor.getBuffer().getEncoding()` as the value for `--encoding` option (with appropriate mapping, if needed).

**Comment by Arcanemagus** [comment]
Sorry I haven't had time to look over this lately, looks like @weirdan put in a PR that should fix this though, as soon as CI passes I'll get that merged and released!

**Comment by irudoy** [comment]
Still having same issue, when file encoding is set to `windows1251` 😞

**Comment by weirdan** [comment]
@irudoy, are you getting errors similar to those in #232 ? `windows1251` is invalid encoding name for some iconv implementations (including built-in on linux).
If so, you may want to monitor that ticket, which (I hope) would get closed soon.

**Comment by irudoy** [comment]
@weirdan ok. I hope that #232 will fix it. Thank you!

**Comment by irudoy** [comment]
Unfortunately, still having issue.
Repro (encoding: `Windows 1251`):
```php
<?php
$q = str_split("ЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭ");
```
Error after saving/modifying file:
`main.js [sm]:371 linter-phpcs:: Invalid point encountered in the attached message`
```json
{
    "message": {
        "message": "Line exceeds 120 characters; contains 125 characters",
        "source": "Generic.Files.LineLength.TooLong",
        "severity": 5,
        "type": "WARNING",
        "line": 2,
        "column": 125,
        "fixable": false
    },
    "source": {
        "lineLength": 72,
        "lineText": "$q = str_split(\"ЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭ\");"
    }
}
```

**Comment by weirdan** [comment]
hmm. Column offset in the error message can only be explained by phpcs getting multibyte string(s) as its input, even though the encoding specified is single byte. I wonder if there's some internal conversion going on. If so, this whole encoding mumbo-jumbo in my latest PRs might be totally irrelevant, even harmful.

**Comment by weirdan** [comment]
> phpcs getting multibyte string(s) as its input, even though the encoding specified is single-byte.

Yep, this is what's actually happening, and what's causing the issue for any single-byte encoding. I posted my analysis as a new ticket (#235).

**Comment by franksl** [comment]
Hi, I encountered this problem on a file that had Mixed line endings (LF and CRLF). After forcing the file to LF the error went away.

**Comment by richarddewit** [comment]
@franksl - I've encountered the same problem and spent some time figuring out what was happening. Seems like CRLF is counted as 2 characters (`\r\n`?) like the multibyte characters as @weirdan stated.

This makes the column point off by 1 (in the case of CRLF).
